version: "3.9"

services:
  mysql:
    image: mysql:8.0
    hostname: mysql
    container_name: baralho-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: baralho
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"