server:
  servlet:
    context-path: /baralho

logging:
  level:
    baralho: ${LOG_LEVEL:DEBUG}

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/baralho?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update